### ISSUE TITLE
How to compute the Pierson-Moskowitz spectrum?

### ISSUE THREAD

**Issue by LeonYin18** [som1990/eWave#1]
Could give more information on how to derivate the Pierson-Moskowitz spectrum?
The code seems wrong.
https://github.com/som1990/eWave/blob/32dedc714e96a536ea2477ab47138d49abd716c6/SG_Wavelet/src/Spectrum.cpp#L30-L33

**Comment by som1990** [comment]
Fixed it to be more clear. I used the code provided by the author from the Water surface Wavelets paper, but their version seemed unclear and incorrect.
